# Generated by Django 4.0.1 on 2022-04-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=14)),
                ('lastName', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=25, unique=True)),
                ('userName', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('passWord', models.CharField(max_length=20)),
            ],
        ),
    ]
